### ISSUE TITLE
Consider using astropy.time for representation of time formats

### ISSUE THREAD

**Issue by Cadair** [MAVENSDC/cdflib#14]
[Astropy Time](http://docs.astropy.org/en/latest/time/) has a lot of machinery for storing and transforming different time formats and epochs, including support for custom transformations. It looks like a lot of the epoch code could be simplified by using some of that functionality.

**Comment by abotiamnot** [comment]
Yes, this would be a great addition! 

Something along the lines of, `cdflib.cdfepoch.time('Epoch')` returning an Astropy Time object.

**Comment by bryan-harter** [comment]
First pass at conversion is located here:

https://github.com/MAVENSDC/cdflib/pull/39

As well as comments about improvements to it.

**Comment by bryan-harter** [comment]
I believe we shouldn't require astropy in order for people to use cdflib, so I added a new optional module that users can use instead of the current epoch class.  

I think the most important features are the TimeFormat classes used for creating the Astropy Time objects, and the "convert_to_astropy" function that takes in CDF_EPOCH/EPOCH16/TT2000 times and turns them into astropy objects.  Then users can convert/utilize the times in the file however they wish.  

But surprisingly, things aren't as smooth as I thought they would be.  A lot of the functionality it quite a bit slower, there is a loss of precision with EPOCH16 values, and there are strange things going on with repeated conversions of the TT2000 data types.  I made tickets for each of these items, and I figured they can be addressed individually.
