### ISSUE TITLE
Why did the interface change, and where's the documentation for the new interface?

### ISSUE THREAD

**Issue by ericthewizard** [MAVENSDC/cdflib#225]
The following worked in v0.4.9:

```
import cdflib
cdf_file = cdflib.CDF('/Users/eric/pydata/mms1/fgm/srvy/l2/2015/10/mms1_fgm_srvy_l2_20151016_v4.18.0.cdf')
cdf_info = cdf_file.cdf_info()
z_vars = cdf_info['zVariables']
```

As of v1.0.0+, we get the error:

```
>>> z_vars = cdf_info['zVariables']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'CDFInfo' object is not subscriptable
```

1. why did this change? since the major version was also bumped, I assume this change in interface was on purpose
2. how does this work now? are there any documentation/examples on how to do this with the new interface?
3. are there other changes to the interface that we should be aware of?
4. is there a way that these changes are being communicated to the developers who reply on this library prior to them being made? perhaps a mailing list that I'm not on?

Thanks!

**Comment by dstansby** [comment]
Yes, this was intentional, to make the library easier to document and maintain. See the changelog (and other pages) for documentation on the new way to do things: https://cdflib.readthedocs.io/en/stable/changelog.html

No mailing list, but the changelog is kept up to date, and the bump in the major version was deliberate because there were so many breaking changes.
